version: '3'

networks:
  ros:
    driver: bridge

services:
  meta:
    image: hypothe/sciroc:meta-noetic
    command: -c "source devel/setup.bash && roslaunch sciroc_meta sciroc_meta_load.launch"
    networks:
      - ros
  ####    
  #logic:
  #  image: hypothe/sciroc:logic-noetic
  #  depends_on:
  #    - pplperc
  #    - objdet
  #    - hri
  #  command: roslaunch sciroc_logic sciroc_control.launch
  #  networks:
  #    - ros
  #  restart: always
  ###
  pplperc:
    image: hypothe/sciroc:pplperc-noetic
    depends_on:
      - meta
    command: -c "source devel/setup.bash && roslaunch people_perception people_perception.launch"
    networks:
      - ros
    restart: always
  ###
  objdet:
    image: hypothe/sciroc:objdet-yolov5-noetic
    depends_on:
      - meta
    command: -c "source devel/setup.bash && roslaunch sciroc_objdet sciroc_objdet_whole_module.launch"
    networks:
      - ros
    restart: always
  ###
  hri:
    image: hypothe/sciroc:hri-noetic
    depends_on:
      - meta
    command: -c "source devel/setup.bash && roslaunch sciroc_hri sciroc_hri.launch"
    networks:
      - ros
    restart: always
  ###